project:
  type: website
  output-dir: docs

website:
  title: "zoozoo-blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme:
      - litera
      - brand
    css: styles.css

execute:
  warning: false
  freeze: auto

